In [1]:
!pip install torch

^C


   ---------------------------------------- 0.0/199.4 MB ? eta -:--:--
   ---------------------------------------- 1.5/199.4 MB 48.6 MB/s eta 0:00:05
    --------------------------------------- 3.7/199.4 MB 47.0 MB/s eta 0:00:05
    --------------------------------------- 4.2/199.4 MB 44.4 MB/s eta 0:00:05
    --------------------------------------- 4.2/199.4 MB 44.4 MB/s eta 0:00:05
    --------------------------------------- 4.2/199.4 MB 44.4 MB/s eta 0:00:05
    --------------------------------------- 4.2/199.4 MB 44.4 MB/s eta 0:00:05
   - -------------------------------------- 6.0/199.4 MB 19.2 MB/s eta 0:00:11
   - -------------------------------------- 8.0/199.4 MB 23.4 MB/s eta 0:00:09
   -- ------------------------------------- 11.0/199.4 MB 25.1 MB/s eta 0:00:08
   -- ------------------------------------- 14.7/199.4 MB 54.4 MB/s eta 0:00:04
   --- ------------------------------------ 18.0/199.4 MB 59.8 MB/s eta 0:00:04
   ---- ----------------------------------- 21.6/199.4 MB


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

In [ ]:
# 0-D Tensor
scalar = torch.tensor(5.0)
number = torch.tensor(1.0)
print(scalar)  # tensor(5.)
print(number) # tensor(1.)

In [ ]:
vector = torch.tensor([1.0, 2.0, 3.0])
tuple_vector = torch.tensor((1, 2, 3))

print(vector)  # tensor([1., 2., 3.])
print(tuple_vector) # tensor([1, 2, 3,])

In [ ]:
matrix = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
matrix2 = torch.tensor([[1, 2, 3], [3, 4, 5]])
print(matrix.shape)
print(matrix2.shape)
# tensor([[1., 2.],
#         [3., 4.]])

In [ ]:
matrix2 = [[1, 2, 3], [3, 4, 5]]
lst = [matrix2, matrix2, matrix2, matrix2]

tensor_3d = torch.tensor([[[1.0], [2.0]], [[3.0], [4.0]]])
tensor_3d_2 = torch.tensor(lst) # len(lst), len(lst[0]), len(lst[0][0]), ....
print(tensor_3d_2.shape)

In [ ]:
print(vector.shape)    # torch.Size([3])
print(matrix.size())   # torch.Size([2, 2])
print(tensor_3d.shape) # torch.Size([2, 2, 1])

In [ ]:
print(vector.dtype)    # torch.float32
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
print(int_tensor.dtype)  # torch.int32

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor_gpu = torch.tensor([1.0, 2.0, 3.0]).to(device)
print(tensor_gpu.device)  # cuda:0 or cpu


In [ ]:
list_tensor = torch.tensor([1, 2, 3])
tuple_tensor = torch.tensor((4, 5, 6))

zeros = torch.zeros((2, 3))
ones = torch.ones((2, 3))
rand = torch.rand((2, 3))
eye = torch.eye(3)  # 3x3 Identity matrix
print(zeros)
print(ones)
print(rand)
print(eye)
normal = torch.randn((2, 3))  # Normal distribution

arange_tensor = torch.arange(start=0, end=10, step=2) # range(0, 10, 2)
linspace_tensor = torch.linspace(start=0, end=1, steps=5) # 0 0.25 0.5 0.75 1
print(arange_tensor)
print(linspace_tensor)
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)


In [ ]:
# write your code here
import random

def nested_list(shape, value = 0):
    """Accepts tuple/list of int, denoting shape of the nested list.
    """
    if len(shape) == 1:
        l = shape[0]
        return [value for _ in range(l)]
    else:
        l = shape[0]
        return [nested_list(shape[1:], value = value) for _ in range(l)]

def random_nested_list(shape, sample_from, *args):
    if len(shape) == 1:
        l = shape[0]
        return [sample_from(*args) for _ in range(l)]
    else:
        l = shape[0]
        return [random_nested_list(shape[1:], sample_from, *args) for _ in range(l)]
'''
def random_nested_list(shape):
    """Accepts tuple/list of int, denoting shape of the nested list.
    """
    if len(shape) == 1:
        l = shape[0]
        return [random.random() for _ in range(l)]
    else:
        l = shape[0]
        return [random_nested_list(shape[1:]) for _ in range(l)]
'''
def randomn_nested_list(shape):
    """Accepts tuple/list of int, denoting shape of the nested list.
    """
    if len(shape) == 1:
        l = shape[0]
        return [random.gauss(0, 1) for _ in range(l)]
    else:
        l = shape[0]
        return [randomn_nested_list(shape[1:]) for _ in range(l)]

def zeros(shape):
    return torch.tensor(nested_list(shape, value = 0))

def ones(shape):
    return torch.tensor(nested_list(shape, value = 1))

def rand(shape):
    return torch.tensor(random_nested_list(shape, random.random))

def randn(shape):
    return torch.tensor(random_nested_list(shape, random.gauss, 0, 1))

print(nested_list((2, 3, 4), value = 0))
print(zeros((2,3,4)) == torch.zeros((2,3,4)))
print(ones((2,3,4)))
print(rand((2,3,4)))
print(randn((2,3,4)))

def eyes(n):
    lst = [[0 for i in range(n)] for j in range(n)]

    lst = []
    for i in range(n):
        tmp = []
        for j in range(n):
            tmp.append(0)
        lst.append(tmp)

    for i in range(n):
        lst[i][i] = 1

    return torch.tensor(lst)

print(eyes(10))

In [ ]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

add = a + b  # tensor([5., 7., 9.])
sub = a - b  # tensor([-3., -3., -3.])

mul = a * b  # tensor([ 4., 10., 18.])
div = b / a  # tensor([4.0000, 2.5000, 2.0000])

exp = a ** 2  # tensor([1., 4., 9.])

In [ ]:
matrix_a = torch.tensor([[1, 2], [3, 4]])
matrix_b = torch.tensor([[5, 6], [7, 8]])
'''
1 2  5 6
3 4  7 8

1 3
2 4
'''
'''
1*5 + 2*7 = 19   1*6 + 2*8 = 22
3*5 + 4*7 = 43   3*6 + 4*8 = 50
'''

matmul = torch.matmul(matrix_a, matrix_b)

# tensor([[19, 22],
#         [43, 50]])

elem_mul = matrix_a * matrix_b
# tensor([[ 5, 12],
#         [21, 32]])

transposed = torch.transpose(matrix_a, 0, 1)
# tensor([[1, 3],
#         [2, 4]])

print(torch.matmul(torch.tensor([[1],[2],[3]]), torch.tensor([[4,5,6]])))


In [ ]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])    # Shape: (2, 3,)
b = torch.tensor([1, 2, 3])                 # Shape: (3,)
b = torch.tensor([[1, 2, 3]])               # Shape: (1, 3,)
b = torch.tensor([[1, 2, 3], [1, 2, 3]])    # Shape: (2, 3,)

broadcast_add = a + b  # Shape: (2, 3)
# tensor([[2, 4, 6],
#         [5, 7, 9]])

a = torch.tensor([[1], [2], [3]])  # Shape: (3, 1)
b = torch.tensor([4, 5, 6])        # Shape: (3,)
b = torch.tensor([[4, 5, 6]])        # Shape: (1, 3,)
b = torch.tensor([[4, 5, 6], [4, 5, 6], [4, 5, 6]])        # Shape: (3, 3,)
a = torch.tensor([[1, 1, 1], [2, 2, 2], [3, 3, 3]])  # Shape: (3, 3)
a*b = [[4, 5, 6], [8, 10, 12], [12, 15, 18]]
# To make shapes compatible:
# a: (3, 1) -> (3, 3)
# b: (3,)   -> (1, 3) -> (3, 3)

broadcast_mul = a * b  # Shape: (3, 3)
# tensor([[ 4,  5,  6],
#         [ 8, 10, 12],
#         [12, 15, 18]])

In [ ]:
a = torch.tensor([-1.0, -2.0, 3.0])

abs_a = torch.abs(a)          # tensor([1., 2., 3.])
# sqrt_a = torch.sqrt(a)
sqrt_a = torch.sqrt(torch.abs(a))  # tensor([1., 1.4142, 1.7321])
exp_a = torch.exp(a)          # tensor([0.3679, 0.1353, 20.0855])
log_a = torch.log(torch.abs(a))    # tensor([0.0000, 0.6931, 1.0986])

In [ ]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

max_ab = torch.max(a, b)  # tensor([4., 5., 6.])
min_ab = torch.min(a, b)  # tensor([1., 2., 3.])


In [ ]:
tensor = torch.tensor([[1, 2, 3], [3, 4, 5]]) # (2,3)

sum_all = torch.sum(tensor)          # tensor(10)
sum_dim0 = torch.sum(tensor, dim=0)  # tensor([4, 6, 8]) (3,)
sum_dim1 = torch.sum(tensor, dim=1)  # tensor([6, 12]) (2,)

mean_all = torch.mean(tensor.float(), dim = 1)  # tensor(2.5000)
print(mean_all)

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([2, 2, 2])

greater = a > b  # tensor([False, False, True])
equal = a == b   # tensor([False, True, False])


In [ ]:
# 임의로 데이터를 한번 만들어 보자.
# True parameters
true_w = 2.0
true_b = 1.0

# Generate data
X = torch.randn(100, 1) * 10  # 100 samples, single feature
y = true_w * X + true_b + torch.randn(100, 1) * 0.2  # Add noise

# y[0]= true_w * X[0] + true_b + torch.randn(1, 1) * 2
# y[1]= true_w * X[1] + true_b + torch.randn(1, 1) * 2
# ...
# y[99]= true_w * X[99] + true_b + torch.randn(1, 1) * 2

# requires_grad = True로 해야 학습이 가능
w = torch.randn(1, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

learning_rate = 0.005
epochs = 5000

for epoch in range(epochs):

    if epoch % 100 == 0:
        print(f'Epoch {epoch}: w = {w.item():.4f}, b = {b.item():.4f}, loss = {loss.item():.4f}')
    # Forward pass: compute predicted y
    # 100, 1 / 1 -> 100, 1 / 1, 1 -> 100, 1 / 100, 1
    y_pred = X * w + b # y_pred: 100, 1

    # Compute and print loss
    loss = torch.mean((y_pred - y) ** 2) # 100, 1

    # Backward pass: compute gradients
    loss.backward()

    # Update parameters using gradient descent
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

    # Zero gradients after updating
    w.grad.zero_()
    b.grad.zero_()




In [ ]:
# y = w1*x1 + w2 * x2 + w3 * x3 + b
import torch

def generate_artificial_data(true_w, true_b, n_data, x_amplitude = 10, noise_amplitude = 0.2):
  X = torch.randn(n_data, 3) * x_amplitude
  y = (true_w[0] * X[:, 0] + true_w[1] * X[:, 1] + true_w[2] * X[:, 2] + true_b + torch.randn(n_data) * noise_amplitude)
  return X, y.view(-1, 1)
def linear_regression(data, learning_rate, epochs, quiet = False):
  X, y = data
  w = torch.randn(3, 1, requires_grad = True)
  b = torch.randn(1, requires_grad = True)

  for epoch in range(epochs):
    y_pred = X @ w + b

    loss = torch.mean((y_pred - y) ** 2)

    if epoch % 100 == 0 and not quiet:
        print(f"Epoch {epoch} : w = {w.view(-1).tolist()}, b = {b.item():.4f}, loss = {loss.item():.4f}")

    loss.backward()

    with torch.no_grad():
      w -= learning_rate * w.grad
      b -= learning_rate * b.grad
    w.grad.zero_()
    b.grad.zero_()
  return w, b
def evaluate_model(true_w, true_b, w, b):

    return (torch.mean((true_w - w.view(-1)) ** 2 / true_w ** 2) + (true_b - b) ** 2 / true_b ** 2).item()

def find_learning_rate():

    true_w = torch.tensor([2.0, -1.0, 3.0]) 
    true_b = 1.0
    data = generate_artificial_data(true_w, true_b, 1000)  
    for learning_rate in [0.0001 * (i + 1) for i in range(10)]:
        w, b = linear_regression(data, learning_rate, 1000, quiet=True)
        score = evaluate_model(true_w, true_b, w, b)
        print(f'Score: {score:.6f}, Learning Rate: {learning_rate}')

data = generate_artificial_data(torch.tensor([2.0, -1.0, 3.0]), 1.0, 1000)
linear_regression(data, 0.001, 1000)


find_learning_rate()